name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  #  pull_request_target:
  #    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      board_config:
        description: "Board configuration to build (leave empty to build all)"
        required: false
        type: choice
        options:
          - ""
          - ARCController
          - ASiLVLABC
          - ASiLVLWASD
          - Blank
          - Pico
          - PicoW
          - Pico2
          - BentoBox
          - FlatboxRev4
          - FlatboxRev5
          - FlatboxRev5RGB
          - FlatboxRev5USBPassthrough
          - FlatboxRev5Southpaw
          - FlatboxRev8
          - Granola
          - GranolaBeacon
          - AdafruitKB2040
          - KeyboardConverter
          - Haute42COSMOX
          - Haute42COSMOXCAS
          - Haute42COSMOXCAT
          - Haute42COSMOXMLite
          - Haute42COSMOXMUltra
          - Haute42COSMOXXAnalog
          - Liatris
          - MavercadeRev1
          - MavercadeRev2
          - MavercadeRev3
          - MiSTercadeV2
          - OpenCore0
          - OpenCore0MIXUP
          - OpenCore0WASD
          - OSUMGP-RP2040
          - PicoFightingBoard
          - PimoroniPicoPlus2
          - PXPGamepad
          - ReflexCtrlGenesis6
          - ReflexCtrlNES
          - ReflexCtrlSaturn
          - ReflexCtrlSNES
          - ReflexCtrlVB
          - ReflexEncodeV1.2
          - ReflexEncodeV2.0
          - RP2040AdvancedBreakoutBoard
          - RP2040AdvancedBreakoutBoardUSBPassthrough
          - RP2040MiniBreakoutBoard
          - RP2040MiniBreakoutBoardUSBPassthrough
          - SeeedXIAORP2040
          - SparkFunProMicro
          - SparkFunProMicroRP2350
          - WaveshareZero
          - WaveshareRP2350BPlusW
          - SGFDevices
          - ZeroRhythm

jobs:
  build:
    uses: ./.github/workflows/build-firmware.yml
    with:
      board-configs: ${{ inputs.board_config }}
      elf-boards: Pico
